# Generated by Django 4.2.1 on 2023-07-14 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('about_text', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('about_html', models.TextField(blank=True, default=None, null=True)),
                ('gravatar_hash', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('display_picture', models.BooleanField(null=True)),
                ('homepage', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('github', models.CharField(blank=True, default=None, max_length=39, null=True)),
                ('comment_karma', models.IntegerField(default=0)),
                ('link_karma', models.IntegerField(default=0)),
            ],
        ),
    ]
